config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :exercises
  resources :recipes

  root 'pages#dashboard'
  get 'library' => 'exercises#index'
  get 'edit_database' => 'exercises#underIndex'
  get "about" => "pages#about"
  get 'workout_generator' => 'workout_gen#index'

  get 'tags/:tag', to: 'recipes#index', as: :tag 

end

app/models/direction.rb
class Direction < ActiveRecord::Base
  belongs_to :recipe
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	enum category: {plyo: 0, legs: 1, push: 2, pull: 3, core: 4, warmUp: 5, coolDown: 6}
	enum impact: {low: 0, medium: 1, high: 2}

	has_attached_file :snapshot, styles: { med: "260X260", }, default_url: "http://placehold.it/260X260"
    validates_attachment_content_type :snapshot, content_type: /\Aimage\/.*\Z/

end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  belongs_to :recipe
end

app/models/reason.rb
class Reason < ActiveRecord::Base
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base

  has_many :ingredients
  has_many :directions
  has_many :reasons

  acts_as_taggable

  accepts_nested_attributes_for :ingredients,
  															reject_if: proc { |attributes| attributes['name'].blank? },
  															allow_destroy: true

 	accepts_nested_attributes_for :directions,
  															reject_if: proc { |attributes| attributes['step'].blank? },
  															allow_destroy: true

  accepts_nested_attributes_for :reasons,
  															reject_if: proc { |attributes| attributes['title'].blank? },
  															allow_destroy: true

  has_attached_file :image, styles: { medium: "400x400#"}, default_url: "http://lorempixel.com/400/400/"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  validates :title, :description, :image, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  before_action :set_exercise, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index, :show, :edit, :update, :destroy]
  before_action :authenticate_admin!, only: [:edit, :update, :destroy]
  # GET /exercises
  # GET /exercises.json
  def index
    @exercises = Exercise.all.order("category ASC")#.paginate(:page => params[:page], :per_page => 52)
  end

  def underIndex
    @exercises = Exercise.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 55)
  end

  # GET /exercises/1
  # GET /exercises/1.json
  def show
  end

  # GET /exercises/new
  def new
    @exercise = Exercise.new
  end

  # GET /exercises/1/edit
  def edit
  end

  # POST /exercises
  # POST /exercises.json
  def create
    @exercise = Exercise.new(exercise_params)

    respond_to do |format|
      if @exercise.save
        format.html { redirect_to @exercise, notice: 'Exercise was successfully created.' }
        format.json { render :show, status: :created, location: @exercise }
      else
        format.html { render :new }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /exercises/1
  # PATCH/PUT /exercises/1.json
  def update
    respond_to do |format|
      if @exercise.update(exercise_params)
        format.html { redirect_to @exercise, notice: 'Exercise was successfully updated.' }
        format.json { render :show, status: :ok, location: @exercise }
      else
        format.html { render :edit }
        format.json { render json: @exercise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /exercises/1
  # DELETE /exercises/1.json
  def destroy
    @exercise.destroy
    respond_to do |format|
      format.html { redirect_to exercises_url, notice: 'Exercise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_exercise
      @exercise = Exercise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def exercise_params
      params.require(:exercise).permit(:category, :exercise, :onesided, :compound, :isolation, :primary, :secondary, :impact, :description, :tip, :snapshot, :video)
    end

  def authenticate_admin!
    # check if current user is admin
    unless current_user.admin
      # if current_user is not admin redirect to some route
      redirect_to root_path
    end
    # if current_user is admin he will proceed to edit action

  def require_login
    unless current_user
      redirect_to root_path
    end
  end

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def landing
	end

	def welcome
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  before_action :find_recipe, only: [:show, :edit, :update, :destroy]

  def index
    if params[:tag]
      @recipe = Recipe.tagged_with(params[:tag]).order("created_at DESC")
    else
      @recipe = Recipe.all.order("created_at DESC")
    end
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    if @recipe.save
      redirect_to @recipe, notice: "Successfully created new recipe"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path, notice: "Successfully deleted recipe!!"
  end

  private

  def recipe_params
    params.require(:recipe).permit(:title, :description, :image, :tag_list, ingredients_attributes:[:id, :name, :amount, :_destroy], directions_attributes:[:id, :step, :_destroy], reasons_attributes:[:id, :title, :description, :_destroy])
  end

  def find_recipe
    @recipe = Recipe.find(params[:id])
  end


end

app/controllers/workout_gen_controller.rb
class WorkoutGenController < ApplicationController
	before_filter :require_login

	def basic
	end


	private

	  def require_login
	    unless current_user
	      redirect_to root_path
	    end
	  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/workout_gen_helper.rb
module WorkoutGenHelper
end

app/views/exercises/_form.html.erb
<%= form_for(@exercise) do |f| %>
  <% if @exercise.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@exercise.errors.count, "error") %> prohibited this exercise from being saved:</h2>

      <ul>
      <% @exercise.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, Exercise.categories.map{ |k, v| [k.humanize, k]} %>
  </div>
  <div class="field">
    <%= f.label :exercise %><br>
    <%= f.text_field :exercise %>
  </div>
  <div class="field">
    <%= f.label :onesided %><br>
    <%= f.check_box :onesided %>
  </div>
  <div class="field">
    <%= f.label :compound %><br>
    <%= f.check_box :compound %>
  </div>
  <div class="field">
    <%= f.label :isolation %><br>
    <%= f.check_box :isolation %>
  </div>
  <div class="field">
    <%= f.label :primary %><br>
    <%= f.text_area :primary %>
  </div>
  <div class="field">
    <%= f.label :secondary %><br>
    <%= f.text_area :secondary %>
  </div>
  <div class="field">
    <%= f.label :impact %><br>
    <%= f.number_field :impact %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :tip %><br>
    <%= f.text_area :tip %>
  </div>
  <div class="field">
    <%= f.label :snapshot %><br>
    <%= f.file_field :snapshot, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :video %><br>
    <%= f.text_field :video, class: "" %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/exercises/edit.html.erb
<h1>Editing Exercise</h1>

<%= render 'form' %>

<%= link_to 'Show', @exercise %> |
<%= link_to 'Back', exercises_path %>

app/views/exercises/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.admin? %>
  <%= link_to 'New Exercise', new_exercise_path %>
<% end %>

<h1 class="title">Full Exercise Library</h1>

<section class="exercises-wrapper">
  <% @exercises.each do |exercise| %>
  <%= link_to exercise do %>
    <div class="exercise-item">
      <%= image_tag exercise.snapshot.url(:medium), :class => "" %>
      <h4><%= exercise.exercise %></h4>
      <p><%= exercise.category %></p>
    </div>
  <% end %>
  <% end %>
</section>

app/views/exercises/new.html.erb
<h1>New Exercise</h1>

<%= render 'form' %>

<%= link_to 'Back', exercises_path %>

app/views/exercises/show.html.erb
<p id="notice"><%= notice %></p>

<section class="main">
  <div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="<%= @exercise.video %>" frameborder="0" allowfullscreen></iframe>
  </div>
  <div class="title">
    <div class="name-cat-wrap">
      <h1><%=  @exercise.exercise %></h1>
      <h6> <%=  @exercise.category %></h6>
    </div>
    <div class="intensity">
      <h4><%=  @exercise.intensity %></h4>
      <h6>Intensity</h6>
    </div>
  </div>
  <div class="details-container">

    <% if @exercise.tip %>
      <div class="tips-container">
        <h4>Tips:</h4>
        <ul class="tips-list">
          <%= @exercise.tip %>
        </ul>
      </div>
    <% end %>

    <% if @exercise.description %>
      <div class="writeup-container">
        <h4>Instructions</h4>
        <p><%= @exercise.description %></p>
      </div>
    <% end %>

    <% if @exercise.primary %>
        <div class="muscle-groups-container">
          <h4>Muscle Groups</h4>
            <p>Primary:  <%= @exercise.primary %> </p>
            <% if @exercise.secondary %>
                <p>Secondary: <%= @exercise.secondary %></p>
            <% end %>
        </div>
    <% end %>

  </div>
</section>

<div>

  <% if current_user.admin? %>
  <%= link_to 'Edit', edit_exercise_path(@exercise) %> |
  <% end %>
  <%= link_to 'Back', exercises_path %>

</div>

app/views/exercises/underIndex.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.admin? %>
  <%= link_to 'New Exercise', new_exercise_path %>
<% end %>

<h1>Listing Exercises</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Category</th>
      <th>Exercise</th>
      <th>Intensity</th>
      <!--
      <th>Onesided</th>
      <th>Compound</th>
      <th>Isolation</th>
      <th>Primary</th>
      <th>Secondary</th>
      <th>Impact</th>-->
      <th>Description</th>
      <th>Tip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.category %></td>
        <td><%= exercise.exercise %></td>
        <td><%= exercise.intensity %></td>
        <!--
        <td><%= exercise.onesided %></td>
        <td><%= exercise.compound %></td>
        <td><%= exercise.isolation %></td>
        <td><%= exercise.primary %></td>
        <td><%= exercise.secondary %></td>
        <td><%= exercise.impact %></td>-->
        <td><%= exercise.description %></td>
        <td><%= exercise.tip %></td>
        <td><%= link_to 'Show', exercise %></td>
        <% if current_user.admin? %>
          <td><%= link_to 'Edit', edit_exercise_path(exercise) %></td>
          <td><%= link_to 'Destroy', exercise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="center">
   <%= will_paginate @exercises, renderer: BootstrapPagination::Rails %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Zoetic", root_path, class: "navbar-brand" %>
    </div>


    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">


        <% if user_signed_in? %>
          <li><%= link_to "Workout", workout_generator_path %></li>
          <li><%= link_to 'Recipes', recipes_path %></li>
          <li><%= link_to "Exercises", library_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
          <li><%= link_to "Sign Up",  new_user_registration_path  %></li>
        <% end %>

        <% if user_signed_in? && current_user.admin? %>
          <li><%= link_to "Edit Database", edit_database_path %></li>
        <% end %>

    </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Zoetic</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <%= render 'layouts/header' %>

 <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
 <% end %>

 <div class="container">
    <%= yield %>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/pages/_landing.html.erb
<div class="jumbotron center">
  <h1>Welcome to Zoetic App!</h1>
  <p>
    <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
    <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
  </p>

</div>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>ZoeticApp is a wellness application built on the three pillars of wellness: fitness, nutritional discovery, and balance.</p>

app/views/pages/dashboard.html.erb
<%= render 'pages/landing' unless user_signed_in? %>

<% if user_signed_in? %>

    <div class="flex-container">
      <div class="flex-item">
        <h4>Workout Generator</h4>
        <%= link_to "Plan Workout", workout_generator_path %>
      </div>
      <div class="flex-item">
        <h4>Learn Exercises</h4>
        <%= link_to "Exercise Library", library_path %>
      </div>
      <div class="flex-item">
        <h4>Plan Meals</h4>
        <%= link_to 'Recipes', recipes_path %>
      </div>
    </div>

<% end %>

app/views/recipes/_direction_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :step, input_html: { class: "form-input form-control" }%>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/_form.html.erb
<%= simple_form_for @recipe, html: { multipart: true } do |f| %>
  <% if @recipe.errors.any? %>
    <div id="errors">
      <p>
        <%= @recipe.errors.count %>
        Prevented this recipe froms saving
      </p>
      <ul>
        <% @recipe.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="panel-body">
    <%= f.input :title, input_html: { class: 'form-control' } %>
    <%= f.input :description, input_html: { class: 'form-control' } %>
    <%= f.input :image, input_html: { class: 'form-control' } %>

    <div class="field">
      <%= f.label :tag_list, "Tags (seperated by commas)" %><br />
      <%= f.text_field :tag_list %>
    </div>

    <div class="row">
      <div class="col-md-12">
        <h3>Reasons To Eat</h3>
        <div id="reasons-to-eat">
          <%= f.simple_fields_for :reasons do |reason| %>
            <%= render 'reason_fields', f: reason %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Reason', f, :reasons, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <h3>Ingredients</h3>
        <div id="ingredients">
          <%= f.simple_fields_for :ingredients do |ingredient| %>
            <%= render 'ingredient_fields', f: ingredient %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Ingredient', f, :ingredients, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
      <div class="col-md-6">
        <h3>Directions</h3>
        <div id="directions">
          <%= f.simple_fields_for :directions do |direction| %>
            <%= render 'direction_fields', f: direction %>
          <% end %>
          <div class="links">
            <%= link_to_add_association 'Add Step', f, :directions, class: "btn btn-default add-button" %>
          </div>
        </div>
      </div>
    </div>

  <%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/recipes/_ingredient_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :name, input_html: { class: "form-input form-control" }%>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/_reason_fields.html.erb
<div class="form-inline clearfix">
  <div class="nested-fields">
    <%= f.input :title, input_html: { class: "form-input form-control" }%>
    <%= f.input :description, input_html: { class: "form-input form-control" }%>
    <%= link_to_remove_association "Remove", f, class: "form-button btn btn-default" %>
  </div>
</div>

app/views/recipes/edit.html.erb
<h1>Edit Recipe</h1>

<%= render 'form' %>

app/views/recipes/index.html.erb
<% if user_signed_in? && current_user.admin? %>
  <div class="new-link">
    <%= link_to 'New Recipe', new_recipe_path %>
  </div>
<% end %>

    <% @recipe.each_slice(3) do |recipes| %>
      <div class="row">
        <% recipes.each do |recipe| %>
          <div class="col-md-4">
            <div class="recipe">
              <div class="image_wrapper">
                <%= link_to recipe do %>
                  <%= image_tag recipe.image.url(:medium) %>
                <% end %>
              </div>
              <h2>
                <%= link_to recipe.title, recipe %>
              </h2>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

app/views/recipes/new.html.erb
<h1>New Recipe</h1>
<%= render 'form' %>
<br/>
<%= link_to "Back", root_path, class: "btn btn-default" %>

app/views/recipes/show.html.erb
<div class="main-content">
  <div class="row" id="recipe_top">
    <div class="col-md-4">
      <%= image_tag @recipe.image.url(:medium), class: "recipe_image" %>
    </div>
    <div class="col-md-8">
      <div id="recipe_info">
        <h1>
          <%= @recipe.title %>
        </h1>
        <p class="description">
          <%= @recipe.description %>
        </p>
        <div id="reasons">
          <h3>Reasons to consider</h3>
          <ol>
            <% @recipe.reasons.each do |reason| %>
              <li>
                <h4><%= reason.title %></h4>
                <p><%= reason.description %></p>
              </li>
            <% end %>
          </ol>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div id="ingredients">
        <h2>Ingredients</h2>
        <ul>
          <% @recipe.ingredients.each do |ingredient| %>
            <li>
              <%= ingredient.name %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <div class="col-md-6">
      <div id="directions">
        <h2>Directions</h2>
        <ul>
          <% @recipe.directions.each do |direction| %>
            <li>
              <%= direction.step %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12 tag-list">
      <h4>Tags</h4>
      <p>
        <%= raw @recipe.tag_list.map { |t| link_to t, tag_path(t) }.join(', ') %>
      </p>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <%= link_to "Back", root_path, class: "btn btn-default" %>
      <% if user_signed_in? && current_user.admin? %>
        <%= link_to "Edit", edit_recipe_path, class: "btn btn-default" %>
        <%= link_to "Delete", recipe_path, method: :delete, data: {confirm: "Are you sure?" }, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/workout_gen/_cooldown.html.erb
<div class="cool-down">
  <div class="cycle-intro">
    <h3 class="title">Cool Down     <span class="glyphicon glyphicon-star" aria-hidden="true"></span></h3>
  </div>


    <div class="exercise-wrapper row">
      <div class="col-sm-1"></div>
      <div class="exercise-category-wrapper col-sm-4">
        <h3 class="exercise-category">Cool Down</h3>
      </div>
      <div class="col-sm-1"></div>
      <div class="exercise-detail-wrapper col-sm-6">
        <h4 class="exercise-name">Full Body Cool Down</h4>
        <a href="//google.com" target="_blank">Details</a>
      </div>

    </div> <!-- close exercise-wrapper -->


</div>

app/views/workout_gen/_firstCircuit.html.erb
        <!-- Fifteen Circuit -->
        <div class="circuit">

          <div class="cycle-wrapper row">

            <div class="cycle-intro">
              <h3 class="title">First Circuit   <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span></h3>
            </div>

            <div class="cycle row" data-bind="foreach: firstCircuit">

              <div class="exercise-wrapper row">
                <div class="col-sm-1"></div>
                <div class="exercise-category-wrapper col-sm-4">
                  <h3 class="exercise-category" data-bind="text: $data.category"></h3>
                </div>
                <div class="col-sm-1"></div>
                <div class="exercise-detail-wrapper col-sm-6">
                  <h4 class="exercise-name" data-bind="text: $data.exercise"></h4>
                  <a data-bind="attr: { href: $data.url }" target="_blank">Details</a>
                </div>

              </div> <!-- close exercise-wrapper -->

            </div> <!-- close cycle 1 -->

          </div> <!-- close cycle wrapper -->

      </div> <!-- close circuit -->

app/views/workout_gen/_secondCircuit.html.erb
        <!-- Fifteen Circuit -->
        <div class="circuit">

          <div class="cycle-wrapper row">

            <div class="cycle-intro">
              <h3 class="title">Second Circuit   <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span></h3>
            </div>

            <div class="cycle row" data-bind="foreach: secondCircuit">

              <div class="exercise-wrapper row">
                <div class="col-sm-1"></div>
                <div class="exercise-category-wrapper col-sm-4">
                  <h3 class="exercise-category" data-bind="text: $data.category"></h3>
                </div>
                <div class="col-sm-1"></div>
                <div class="exercise-detail-wrapper col-sm-6">
                  <h4 class="exercise-name" data-bind="text: $data.exercise"></h4>
                  <a data-bind="attr: { href: $data.url }" target="_blank">Details</a>
                </div>

              </div> <!-- close exercise-wrapper -->

            </div> <!-- close cycle 1 -->

          </div> <!-- close cycle wrapper -->

      </div> <!-- close circuit -->

app/views/workout_gen/_thirdCircuit.html.erb
        <!-- Fifteen Circuit -->
        <div class="circuit">

          <div class="cycle-wrapper row">

            <div class="cycle-intro">
              <h3 class="title">Third Circuit   <span class="glyphicon glyphicon-refresh" aria-hidden="true"></span></h3>
            </div>

            <div class="cycle row" data-bind="foreach: thirdCircuit">

              <div class="exercise-wrapper row">
                <div class="col-sm-1"></div>
                <div class="exercise-category-wrapper col-sm-4">
                  <h3 class="exercise-category" data-bind="text: $data.category"></h3>
                </div>
                <div class="col-sm-1"></div>
                <div class="exercise-detail-wrapper col-sm-6">
                  <h4 class="exercise-name" data-bind="text: $data.exercise"></h4>
                  <a data-bind="attr: { href: $data.url }" target="_blank">Details</a>
                </div>

              </div> <!-- close exercise-wrapper -->

            </div> <!-- close cycle 1 -->

          </div> <!-- close cycle wrapper -->

      </div> <!-- close circuit -->

app/views/workout_gen/_warmup.html.erb
<div class="warm-up">
  <div class="cycle-intro">
    <h3 class="title">Warm Up     <span class="glyphicon glyphicon-heart-empty" aria-hidden="true"></span></h3>
  </div>

    <div class="exercise-wrapper row">


      <div class="exercise-category-wrapper col-sm-4">
        <h3 class="exercise-category">Warm Up</h3>
      </div>

      <div class="exercise-detail-wrapper col-sm-6">
        <h4 class="exercise-name">Full Body Warm Up</h4>
        <a href="//google.com" target="_blank">Details</a>
      </div>

    </div> <!-- close exercise-wrapper -->


</div>

app/views/workout_gen/_waterbreak.html.erb
<!-- water break -->
  <div class="cycle-intro">
    <h3 class="title">Water Break     <span class="glyphicon glyphicon-tint" aria-hidden="true"></span></h3>
    <p class="exercise-time">30 Seconds After Each Cycle</p>
  </div>

app/views/workout_gen/index.html.erb
    <div class="controls">
        <div class="time-container">
          <h4 class="text-center">Circuits</h4>
          <div class="btn-group btn-group-justified" role="group" aria-label="...">
              <div class="btn-group" role="group">
                <button type="button" class="btn btn-default" data-bind="click: function() {selectedWorkout(1); todaysWorkout(0)}">1</button>
              </div>
              <div class="btn-group" role="group">
                <button type="button" class="btn btn-default" data-bind="click: function() {selectedWorkout(2); todaysWorkout(0)}">2</button>
              </div>
              <div class="btn-group" role="group">
                <button type="button" class="btn btn-default" data-bind="click: function() {selectedWorkout(3); todaysWorkout(0)}">3</button>
              </div>
          </div>
        </div>

        <div class="intensity-container">
          <h4 class="text-center">Intensity<!--<span id="slide-value" data-bind="text: selectedIntensity"></span>--></h4>
          <div id="intensitySlider"></div>
        </div>
        <btn id="generate" class="center"><strong>GENERATE WORKOUT</strong></btn>
    </div>

    <div class="todaysWorkout" data-bind="if: (todaysWorkout() === 1)">

      <!-- warm up -->
      <div class="fifteenMin">
        <%= render 'workout_gen/warmup' %>
      </div>

      <!-- first circuit -->
      <div class="fifteenMin" data-bind="if: (firstCircuit().length > 2) ">
        <%= render 'workout_gen/firstCircuit' %>
      </div>

      <!-- second circuit -->
      <div class="fifteenMin" data-bind="if: (secondCircuit().length > 3)">
        <%= render 'workout_gen/secondCircuit' %>
      </div>

      <!-- third circuit -->
      <div class="fifteenMin" data-bind="if: (thirdCircuit().length > 3) ">
        <%= render 'workout_gen/thirdCircuit' %>
      </div>


      <!-- cooldown -->
      <div class="fifteenMin">
        <%= render 'workout_gen/cooldown' %>
      </div>

    </div> <!-- close todaysWorkout -->